version: '3.2'

volumes:
  mysql_data:
  mysql_data_test:

services:
  mysql:
    image: public.ecr.aws/dashhudson/mysql:5.7.36
    environment:
      MYSQL_ROOT_PASSWORD: 'very_secure_password'
      MYSQL_DATABASE: 'connections_db'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=']
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3307:3306"

  mysql_test:
    image: public.ecr.aws/dashhudson/mysql:5.7.36
    environment:
      MYSQL_ROOT_PASSWORD: 'very_secure_password'
      MYSQL_DATABASE: 'connections_db_test'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=']
    volumes:
      - mysql_data_test:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"

  connections:
    image: connections:dev
    restart: always
    build: .
    env_file:
      - .local.env
    command: >
      gunicorn -b 0.0.0.0:5005
      --access-logfile -
      --reload
      connections:app
    expose:
      - "5005"
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    depends_on:
      - mysql
