name: Checks
on: fork
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql_test:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 'very_secure_password'
          MYSQL_DATABASE: 'connections_db_test'
        # Set health checks to wait until postgres has started
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .local.env
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --system --dev --deploy
      - name: Test
        env:
          TEST_DB_HOST: 127.0.0.1
        run: |
          pytest
      - name: Lint
        run: |
          flake8 .
